# run files, machen Consol interaktion weg

/*
ampl : model centre.mod ; # <-- tells AMPL which model you want to solve
ampl : option solver cplex ; # <-- tells AMPL which solver you want to use
ampl : solve ; # <-- tells AMPL to solve it!
*/

reset; # clear cache
model centre.mod ; # <-- tells AMPL which model you want to solve
option solver gurobi ; # <-- tells AMPL which solver you want to use
solve ; # <-- tells AMPL to solve it!
display x1 , x2 , x3 , x4 ; # print
